version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_MONGO_URL=mongodb://mongo:27017/instrument-shop
      - NEXT_PUBLIC_NODE_ENV=development
    volumes:
      - ./backend:/code
    networks:
      - express-network

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - express-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - express-network

volumes:
  mongo_data:

networks:
  express-network:
